name: prod app release
run-name: ${{ github.actor }} triggered manually prod release - ${{ github.ref }}
on:
  workflow_dispatch:

env:
  FILE_NAME: pipeline-${{ github.run_number }}
  ROOT_PATH_DOWNLOAD: /home/runner/work/pipeline-github-actions/pipeline-github-actions

jobs:
  install-and-test:
    name: Install and test
    runs-on: ubuntu-latest

    steps:
      ## prepare environment with cashing
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Find yarn cache
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install npm dependencies
        run: yarn install --immutable

      - name: Linting check
        run: yarn lint:fix

      - name: Run unit tests
        run: yarn test

  build-android:
    name: Build Android
    needs: install-and-test
    runs-on: ubuntu-latest

    steps:
      ## prepare environment with cashing
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      ## cache node modules
      - name: Find yarn cache
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install npm dependencies
        run: yarn install --immutable

      ## cache gradle
      - name: Cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew

      ## build .apk
      - name: Build Android release .apk
        run: |
          cd android && ./gradlew assembleRelease && cd ..

      ## sign .apk
      - name: Sign .apk
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      ## upload artifact .apk to GHA
      - name: Upload artifact .apk to GHA
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE_NAME }}.apk
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}

      ## build .aab
      - name: Build Android release .aab
        run: |
          cd android && ./gradlew bundleRelease

      ## sign .aab
      - name: Sign .aab
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      ## upload artifact .aab to GHA
      - name: Upload artifact .abb to GHA
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE_NAME }}.aab
          path: ${{steps.sign_aab.outputs.signedReleaseFile}}

      # ## distribute .aab to Google play store
      # - name: Upload .abb to Google play store
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON_TEXT }}
      #     packageName: com.savczukinv.pipeline
      #     releaseFiles: ${{steps.sign_aab.outputs.signedReleaseFile}}
      #     track: production
      #     status: draft
      #     inAppUpdatePriority: 2

  build-ios:
    name: Build iOS
    needs: install-and-test
    runs-on: macos-latest

    steps:
      ## prepare environment with cashing
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      ## cache node modules
      - name: Find yarn cache
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install npm dependencies
        run: yarn install --immutable

      ## cache pods
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.5"
          bundler-cache: true

      - name: Restore pods cache
        uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install pods dependencies
        run: cd ios && pod install && cd ..

      ## build and sign .ipa
      - name: Build and sign .ipa
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: ios/pipeline.xcodeproj
          workspace-path: ios/pipeline.xcworkspace
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          code-signing-identity: "iPhone Distribution"
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          output-path: "pipeline.ipa"

      ## upload artifact .ipa to GHA
      - name: Upload artifact .ipa to GHA
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE_NAME }}.ipa
          path: pipeline.ipa

  distribute-android-google-play:
    name: Distribute Android to Google play
    needs: build-android
    runs-on: ubuntu-latest

    steps:
      ## repo checkout
      - name: Repo checkout
        uses: actions/checkout@v3

      ## download .aab
      - name: Download .aab
        id: download_aab
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.FILE_NAME }}.aab

      ## distribute .aab to Google play store
      - name: Distribute .abb to Google play store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON_TEXT }}
          packageName: com.savczukinv.pipeline
          releaseFiles: ${{ env.ROOT_PATH_DOWNLOAD }}/app-release-unsigned-signed.aab
          track: production
          status: draft
          inAppUpdatePriority: 2

  distribute-ios-test-flight:
    name: Distribute iOS to TestFlight
    needs: build-ios
    runs-on: ubuntu-latest

    steps:
      ## repo checkout
      - name: Repo checkout
        uses: actions/checkout@v3

      ## download .ipa
      - name: Download .ipa
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.FILE_NAME }}.ipa

      ## distribute .ipa to Test Flight
      - name: Distribute .ipa to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: ${{ env.ROOT_PATH_DOWNLOAD }}/pipeline.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
