name: prod-env-build
run-name: ${{ github.actor }} triggered github action
on:
  push:
    branches:
      - main
jobs:
  # install-and-test:
  #   name: Install and test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - run: echo "Prepare test environment"
  #     - name: repo checkout
  #       uses: actions/checkout@v3

  #     - name: install node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16.15.0

  #     - name: install npm packages
  #       run: npm install --force

  #     - name: linting
  #       run: npm run lint:fix

  #     - name: run unit tests
  #       run: npm run test

  # - name: Jest coverage report
  #   uses: ArtiomTr/jest-coverage-report-action@v2.0.6
  #   with:
  #     coverage-file: ./jest-report.json
  #     base-coverage-file: ./jest-report.json

  android-build:
    name: Android build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Prepare Android environment"
      - name: repo checkout
        uses: actions/checkout@v3

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Install npm packages
        run: npm install --force

      ## build apk
      - name: build Android release .apk
        run: |
          cd android && ./gradlew assembleRelease

      ## sign apk
      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      ## Distribute apk to Firebase App Distribution
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: ${{steps.sign_app.outputs.signedReleaseFile}}
          releaseNotes: "Release .apk"

      ## build aab
      - name: Build Android release .aab
        run: |
          cd android && ./gradlew bundleRelease --no-daemon

      ## sign aab
      - name: Sign .aab
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      # - name: Distribute app to Firebase app distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
      #   with:
      #     appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
      #     # token: ${{secrets.ANDROID_FIREBASE_TOKEN}}
      #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
      #     groups: testers
      #     file: android/app/build/outputs/bundle/release/app-release.aab
      #     releaseNotes: "Release .aab"

      ## Distribute aab to Google play store
      - name: Upload app to Google play store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON_TEXT }}
          packageName: com.savczukinv.pipeline
          releaseFiles: android/app/build/outputs/bundle/release/*.aab
          track: production
          status: draft
          inAppUpdatePriority: 2

      # - name: Upload Artifact to Github Actions
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: "my-app-release-${{ github.run_number }}.apk"
      #     path: android/app/build/outputs/apk/release/my-app-release.apk

  # ios-build:
  #   runs-on: macos-12
  #   steps:
  #     - run: echo "Prepare iOS environment"
  #     - name: repo checkout
  #       uses: actions/checkout@v3

  #     - name: install node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16.15.0

  #     - name: install npm packages
  #       run: npm install --force

  #     - name: install pod dependencies
  #       run: |
  #         cd ios && pod install && cd ..

  #     - name: build iOS release
  #       uses: yukiarrr/ios-build-action@v1.4.0

  #     - name: Upload Artifact to Github Actions
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: "my-app-release-${{ github.run_number }}.ipa"
  #         path: /Users/runner/work/my-app/my-app/my-app-release.ipa
