name: test-env-build
run-name: ${{ github.actor }} triggered github action
on:
  push:
    branches:
      - develop
jobs:
  # install-and-test:
  #   name: Install and test
  #   runs-on: ubuntu-latest

  #   steps:
  #     ## prepare environment
  #     - name: Repo checkout
  #       uses: actions/checkout@v3

  #     - name: Install node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16.15.0

  #     - name: Install npm packages
  #       run: npm install --force

  #     - name: Linting check
  #       run: npm run lint:fix

  #     - name: Run unit tests
  #       run: npm run test

  # - name: Jest coverage  report
  #   uses: ArtiomTr/jest-coverage-report-action@v2.0.6
  #   with:
  #     coverage-file: ./jest-report.json
  #     base-coverage-file: ./jest-report.json

  android-build:
    name: Android build
    runs-on: ubuntu-latest
    steps:
      ## prepare environment
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Install npm packages
        run: npm install --force

      ## build apk
      - name: Build Android release .apk
        run: |
          cd android && ./gradlew assembleRelease --no-daemon && cd ..

      ## sign apk
      - name: Sign .apk
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      ## Distribute apk to Firebase App Distribution
      - name: Upload .apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
          # serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          token: ${{secrets.ANDROID_FIREBASE_TOKEN}}
          groups: testers
          file: ${{steps.sign_apk.outputs.signedReleaseFile}}
          releaseNotes: "Test .apk"

  # ios-build:
  #   runs-on: macos-12
  #   steps:
  #     - run: echo "Prepare iOS environment"
  #     - name: repo checkout
  #       uses: actions/checkout@v3

  #     - name: install node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16.15.0

  #     - name: install npm packages
  #       run: npm install --force

  #     - name: install pod dependencies
  #       run: |
  #         cd ios && pod install && cd ..

  #     - name: build iOS release
  #       uses: yukiarrr/ios-build-action@v1.4.0

  #     - name: Upload Artifact to Github Actions
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: "my-app-release-${{ github.run_number }}.ipa"
  #         path: /Users/runner/work/my-app/my-app/my-app-release.ipa
